service: github-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.getCommits
    events:
      - http:
          path: commits/
          method: get